function [col_names, this_data] = dataFromSort( newsort )
%dataFromSort formats column names and data for database insertion
col_names = {'sort_id', 'processed_mat', 'comments', 'user', 'origin',...            
        's_file', 't_file', 'recording_fid'};
    ssdirq = ['SELECT path FROM machines WHERE m_name = ' getenv('username')];
    ssdir = fetch(conn,ssdirq); ssdir = ssdir{1};
    subj = whichSubj(newsort.name(1));
    this_data = {[],[ssdir 'processed\' subj '\'  newsort.name '.mat'],...
        newsort.comments, ...
        newsort.user, ...
        newsort.origin, ...
        [ssdir 'processed\' subj '\Spike2Exports\'  newsort.name 's.mat'], ...
        [ssdir 'processed\' subj '\Spike2Exports\'  newsort.name 't.mat'], ...
        newsort.parent};
end

